### ISSUE TITLE
latest version breaks install / running of apps

### ISSUE THREAD

**Issue by cvlmtg** [tinganho/l10ns#167]
Hi, looks like the latest version of l10ns breaks with this error:

```
    Error: Cannot find module 'update-notifier'
        at Function.Module._resolveFilename (module.js:469:15)
        at Function.Module._load (module.js:417:25)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/usr/local/bsmart/shared/html5-app/node_modules/l10ns/binaries/l10ns:19:22)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
```

**Comment by qborreda** [comment]
Happens to us as well. Had to fall down to 2.4.11

**Comment by sveinhal** [comment]
Same issue. Breaks in ea8922dcca3c9ae5b61ff520fc4bbf3223c90c77

**Comment by tinganho** [comment]
The latest should have pointed to 2.4.11. Sorry for the inconvenience. It should be fixed now.
